name: AKS Deploy

on:
  push:
    branches:
      - main

concurrency:
  group: opentofu-deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup OpenTofu
      uses: opentofu/setup-opentofu@v1

    - name: OpenTofu Init
      run: tofu init

    - name: OpenTofu Validate
      run: tofu validate

    - name: OpenTofu Plan
      run: tofu plan

    - name: OpenTofu Apply
      run: tofu apply -auto-approve